# Builder stage
FROM --platform=$BUILDPLATFORM golang:1.26 AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /src
ADD . .
RUN CGO_ENABLED=0 \
    GOOS=$TARGETOS \
    GOARCH=$TARGETARCH \
    go build -a -ldflags="-s -w" -o app .
RUN chmod +x app

# Runner Stage
FROM alpine:edge
RUN apk add --no-cache libc6-compat
RUN apk add --no-cache tzdata
RUN apk add --no-cache iputils-ping
RUN mkdir /app
WORKDIR /app
COPY --from=builder /src/app /app/app
CMD ["/app/app", "start"]
EXPOSE 3000
