# Builder stage
FROM golang:1.22 AS builder

WORKDIR /src
ADD . .
RUN go build -o app .

# Runner Stage
FROM alpine:edge
RUN apk add --no-cache libc6-compat
RUN apk add --no-cache tzdata
RUN apk add --no-cache iputils-ping
RUN mkdir /app
WORKDIR /app
COPY --from=builder /src/app /app/app
CMD ["/app/app", "start"]
EXPOSE 3000
