version: "3"
services:
  app:
    networks:
      - app
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - "../:/app"

  # app-workers:
  #   networks:
  #     - app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.Workers
  #   container_name: app-workers
  #   security_opt:
  #     - seccomp:unconfined
  #   env_file: .env
  #   volumes:
  #     - "../:/app"
  #   depends_on:
  #     - app
  
networks:
  app:
