// Code generated by mockery v2.50.0. DO NOT EDIT.

package wrappers

import mock "github.com/stretchr/testify/mock"

// FileSystemWrapperMock is an autogenerated mock type for the FileSystemWrapper type
type FileSystemWrapperMock struct {
	mock.Mock
}

// CreateDirectory provides a mock function with given fields: path
func (_m *FileSystemWrapperMock) CreateDirectory(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirectory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroy provides a mock function with given fields: path
func (_m *FileSystemWrapperMock) Destroy(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteFile provides a mock function with given fields: path, data
func (_m *FileSystemWrapperMock) WriteFile(path string, data string) error {
	ret := _m.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFileSystemWrapperMock creates a new instance of FileSystemWrapperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystemWrapperMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystemWrapperMock {
	mock := &FileSystemWrapperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
