// Code generated by mockery v2.50.0. DO NOT EDIT.

package wrappers

import mock "github.com/stretchr/testify/mock"

// MockShellWrapper is an autogenerated mock type for the ShellWrapper type
type MockShellWrapper struct {
	mock.Mock
}

// Exec provides a mock function with given fields: name, args
func (_m *MockShellWrapper) Exec(name string, args ...string) ([]byte, error) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) ([]byte, error)); ok {
		return rf(name, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) []byte); ok {
		r0 = rf(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(name, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockShellWrapper creates a new instance of MockShellWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShellWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShellWrapper {
	mock := &MockShellWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
