// Code generated by mockery v2.50.0. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// FileSystemRepoMock is an autogenerated mock type for the FileSystemRepo type
type FileSystemRepoMock struct {
	mock.Mock
}

// CreateDirectory provides a mock function with given fields: path
func (_m *FileSystemRepoMock) CreateDirectory(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirectory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteFile provides a mock function with given fields: path, data
func (_m *FileSystemRepoMock) WriteFile(path string, data string) error {
	ret := _m.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFileSystemRepoMock creates a new instance of FileSystemRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystemRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystemRepoMock {
	mock := &FileSystemRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
