// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/tech-thinker/gozen/models"
)

// NewMockProjectRepo creates a new instance of MockProjectRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepo {
	mock := &MockProjectRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectRepo is an autogenerated mock type for the ProjectRepo type
type MockProjectRepo struct {
	mock.Mock
}

type MockProjectRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepo) EXPECT() *MockProjectRepo_Expecter {
	return &MockProjectRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProjectRepo
func (_mock *MockProjectRepo) Create(project models.Project) error {
	ret := _mock.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Project) error); ok {
		r0 = returnFunc(project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - project models.Project
func (_e *MockProjectRepo_Expecter) Create(project interface{}) *MockProjectRepo_Create_Call {
	return &MockProjectRepo_Create_Call{Call: _e.mock.On("Create", project)}
}

func (_c *MockProjectRepo_Create_Call) Run(run func(project models.Project)) *MockProjectRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Project
		if args[0] != nil {
			arg0 = args[0].(models.Project)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectRepo_Create_Call) Return(err error) *MockProjectRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepo_Create_Call) RunAndReturn(run func(project models.Project) error) *MockProjectRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}
