// Code generated by mockery v2.50.0. DO NOT EDIT.

package repository

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/tech-thinker/gozen/models"
)

// ProjectRepoMock is an autogenerated mock type for the ProjectRepo type
type ProjectRepoMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: project
func (_m *ProjectRepoMock) Create(project models.Project) error {
	ret := _m.Called(project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Project) error); ok {
		r0 = rf(project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProjectRepoMock creates a new instance of ProjectRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectRepoMock {
	mock := &ProjectRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
