# Environments

# Load .env file
ifneq (,$(wildcard .env))
    include .env
    export $(shell sed 's/=.*//' .env)
endif

test:
	go test -v ./...  -race -coverprofile=coverage.out -covermode=atomic

coverage: test
	go tool cover -func=coverage.out

coverage-html: test
	mkdir -p coverage
	go tool cover -html=coverage.out -o coverage/index.html

coverage-serve: coverage-html
	python3 -m http.server 8080 -d coverage

setup:
	go mod tidy

run:
	go run main.go start

build:
	go build -o {{.AppName}}

clean:
	rm -rf {{.AppName}}

generate-protoc:
	protoc --go_out=. --go-grpc_out=. app/grpc/proto/*.proto

install-protoc:
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.35.2
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

uninstall-protoc:
	rm $(GOPATH)/bin/protoc-gen-go
	rm $(GOPATH)/bin/protoc-gen-go-grpc
